[phases.setup]
packages = ["python39", "python39-pip", "gcc", "postgresql"]

[phases.install]
cmds = ["python3.9 -m pip install --upgrade pip", "python3.9 -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"
runtime = "python"