[phases.setup]
packages = ["python3.9", "python3.9-pip", "python3.9-dev", "gcc", "postgresql"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"
runtime = "python"