[phases.setup]
packages = ["python39", "gcc", "postgresql"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"
runtime = "python"